Name:           ros-jade-moveit-msgs
Version:        0.8.4
Release:        0%{?dist}
Summary:        ROS moveit_msgs package

Group:          Development/Libraries
License:        BSD
URL:            http://moveit.ros.org
Source0:        %{name}-%{version}.tar.gz

Requires:       ros-jade-actionlib-msgs
Requires:       ros-jade-geometry-msgs
Requires:       ros-jade-message-runtime
Requires:       ros-jade-object-recognition-msgs
Requires:       ros-jade-octomap-msgs
Requires:       ros-jade-sensor-msgs
Requires:       ros-jade-shape-msgs
Requires:       ros-jade-std-msgs
Requires:       ros-jade-trajectory-msgs
BuildRequires:  ros-jade-actionlib-msgs
BuildRequires:  ros-jade-catkin
BuildRequires:  ros-jade-geometry-msgs
BuildRequires:  ros-jade-message-generation
BuildRequires:  ros-jade-object-recognition-msgs
BuildRequires:  ros-jade-octomap-msgs
BuildRequires:  ros-jade-sensor-msgs
BuildRequires:  ros-jade-shape-msgs
BuildRequires:  ros-jade-std-msgs
BuildRequires:  ros-jade-trajectory-msgs

%description
Messages, services and actions used by MoveIt

%prep
%setup -q

%build
# In case we're installing to a non-standard location, look for a setup.sh
# in the install tree that was dropped by catkin, and source it.  It will
# set things like CMAKE_PREFIX_PATH, PKG_CONFIG_PATH, and PYTHONPATH.
if [ -f "/opt/ros/jade/setup.sh" ]; then . "/opt/ros/jade/setup.sh"; fi
mkdir -p obj-%{_target_platform} && cd obj-%{_target_platform}
%cmake .. \
        -UINCLUDE_INSTALL_DIR \
        -ULIB_INSTALL_DIR \
        -USYSCONF_INSTALL_DIR \
        -USHARE_INSTALL_PREFIX \
        -ULIB_SUFFIX \
        -DCMAKE_INSTALL_LIBDIR="lib" \
        -DCMAKE_INSTALL_PREFIX="/opt/ros/jade" \
        -DCMAKE_PREFIX_PATH="/opt/ros/jade" \
        -DSETUPTOOLS_DEB_LAYOUT=OFF \
        -DCATKIN_BUILD_BINARY_PACKAGE="1" \

make %{?_smp_mflags}

%install
# In case we're installing to a non-standard location, look for a setup.sh
# in the install tree that was dropped by catkin, and source it.  It will
# set things like CMAKE_PREFIX_PATH, PKG_CONFIG_PATH, and PYTHONPATH.
if [ -f "/opt/ros/jade/setup.sh" ]; then . "/opt/ros/jade/setup.sh"; fi
cd obj-%{_target_platform}
make %{?_smp_mflags} install DESTDIR=%{buildroot}

%files
/opt/ros/jade

%changelog
* Tue Nov 15 2016 Dave Coleman <dave@dav.ee> - 0.8.4-0
- Autogenerated by Bloom

* Mon Aug 22 2016 Dave Coleman <dave@dav.ee> - 0.8.3-0
- Autogenerated by Bloom

* Sat Aug 20 2016 Dave Coleman <dave@dav.ee> - 0.8.2-0
- Autogenerated by Bloom

* Wed Jun 15 2016 Ioan Sucan <isucan@google.com> - 0.8.1-0
- Autogenerated by Bloom

* Thu Apr 21 2016 Ioan Sucan <isucan@google.com> - 0.8.0-0
- Autogenerated by Bloom

* Thu Apr 21 2016 Ioan Sucan <isucan@google.com> - 0.7.1-0
- Autogenerated by Bloom

* Thu Apr 30 2015 Ioan Sucan <isucan@google.com> - 0.6.1-0
- Autogenerated by Bloom

