Name:           ros-kinetic-moveit-msgs
Version:        0.9.1
Release:        0%{?dist}
Summary:        ROS moveit_msgs package

Group:          Development/Libraries
License:        BSD
URL:            http://moveit.ros.org
Source0:        %{name}-%{version}.tar.gz

Requires:       ros-kinetic-actionlib-msgs
Requires:       ros-kinetic-geometry-msgs
Requires:       ros-kinetic-message-runtime
Requires:       ros-kinetic-object-recognition-msgs
Requires:       ros-kinetic-octomap-msgs
Requires:       ros-kinetic-sensor-msgs
Requires:       ros-kinetic-shape-msgs
Requires:       ros-kinetic-std-msgs
Requires:       ros-kinetic-trajectory-msgs
BuildRequires:  ros-kinetic-actionlib-msgs
BuildRequires:  ros-kinetic-catkin
BuildRequires:  ros-kinetic-geometry-msgs
BuildRequires:  ros-kinetic-message-generation
BuildRequires:  ros-kinetic-object-recognition-msgs
BuildRequires:  ros-kinetic-octomap-msgs
BuildRequires:  ros-kinetic-sensor-msgs
BuildRequires:  ros-kinetic-shape-msgs
BuildRequires:  ros-kinetic-std-msgs
BuildRequires:  ros-kinetic-trajectory-msgs

%description
Messages, services and actions used by MoveIt

%prep
%setup -q

%build
# In case we're installing to a non-standard location, look for a setup.sh
# in the install tree that was dropped by catkin, and source it.  It will
# set things like CMAKE_PREFIX_PATH, PKG_CONFIG_PATH, and PYTHONPATH.
if [ -f "/opt/ros/kinetic/setup.sh" ]; then . "/opt/ros/kinetic/setup.sh"; fi
mkdir -p obj-%{_target_platform} && cd obj-%{_target_platform}
%cmake .. \
        -UINCLUDE_INSTALL_DIR \
        -ULIB_INSTALL_DIR \
        -USYSCONF_INSTALL_DIR \
        -USHARE_INSTALL_PREFIX \
        -ULIB_SUFFIX \
        -DCMAKE_INSTALL_LIBDIR="lib" \
        -DCMAKE_INSTALL_PREFIX="/opt/ros/kinetic" \
        -DCMAKE_PREFIX_PATH="/opt/ros/kinetic" \
        -DSETUPTOOLS_DEB_LAYOUT=OFF \
        -DCATKIN_BUILD_BINARY_PACKAGE="1" \

make %{?_smp_mflags}

%install
# In case we're installing to a non-standard location, look for a setup.sh
# in the install tree that was dropped by catkin, and source it.  It will
# set things like CMAKE_PREFIX_PATH, PKG_CONFIG_PATH, and PYTHONPATH.
if [ -f "/opt/ros/kinetic/setup.sh" ]; then . "/opt/ros/kinetic/setup.sh"; fi
cd obj-%{_target_platform}
make %{?_smp_mflags} install DESTDIR=%{buildroot}

%files
/opt/ros/kinetic

%changelog
* Mon Feb 06 2017 Dave Coleman <dave@dav.ee> - 0.9.1-0
- Autogenerated by Bloom

* Tue Nov 15 2016 Dave Coleman <dave@dav.ee> - 0.9.0-0
- Autogenerated by Bloom

* Mon Aug 22 2016 Dave Coleman <dave@dav.ee> - 0.8.3-0
- Autogenerated by Bloom

* Sat Aug 20 2016 Dave Coleman <dave@dav.ee> - 0.8.2-0
- Autogenerated by Bloom

* Mon Aug 15 2016 Ioan Sucan <isucan@google.com> - 0.8.1-0
- Autogenerated by Bloom

